apiVersion: v1
kind: ServiceMonitor
metadata:
  name: pytorch-training-metrics
  namespace: pytorch-training
  labels:
    app: pytorch-training
spec:
  selector:
    matchLabels:
      app: pytorch-training
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: pytorch-training-metrics
  namespace: pytorch-training
  labels:
    app: pytorch-training
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: pytorch-training
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: training-monitoring-config
  namespace: pytorch-training
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'pytorch-training'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - pytorch-training
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: pytorch-training
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-log-collector
  namespace: pytorch-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-log-collector
  template:
    metadata:
      labels:
        app: training-log-collector
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch.logging.svc.cluster.local"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: fluentd-config
      - name: varlog
        hostPath:
          path: /var/log